# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0002_auto_20161114_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='createdBy',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='programmingLanguage',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='speciality',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='yearsOfExperience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
