# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161207_0502'),
        ('CompaniesApp', '0002_auto_20161114_0645'),
        ('GroupsApp', '0002_group_project'),
        ('AuthenticationApp', '0002_engineer_professor_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='companies',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='projects',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='programmingLanguage',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='speciality',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='yearsOfExperience',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GroupsApp.Group'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='university',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
    ]
