# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0005_auto_20161114_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='photo',
            field=models.ImageField(blank=True, default='static/universityimages/purdue.jpg', null=True, upload_to='static/universityimages'),
        ),
    ]
